# Generated by Django 4.1.5 on 2023-01-19 12:08

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plancost",
            options={
                "ordering": (
                    "recurrence_unit",
                    "recurrence_period",
                    "cost",
                    "crypto_amount",
                )
            },
        ),
        migrations.AddField(
            model_name="plancost",
            name="crypto_amount",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=18,
                default_currency="ETH",
                help_text="If payment is made in crypto.",
                max_digits=24,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plancost",
            name="crypto_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("ETH", "Ether"), ("KLAY", "Klay"), ("SOL", "Sol")],
                default="ETH",
                editable=False,
                max_length=4,
                null=True,
            ),
        ),
    ]
