# Generated by Django 4.1.4 on 2023-01-18 11:13

from django.db import migrations, models
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions_api", "0010_plancost_min_subscription_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="plancost",
            name="uuid",
            field=django_extensions.db.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID().uuid,
                editable=False,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="planlist",
            name="uuid",
            field=django_extensions.db.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID().uuid,
                editable=False,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="planlistdetail",
            name="uuid",
            field=django_extensions.db.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID().uuid,
                editable=False,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plantag",
            name="uuid",
            field=django_extensions.db.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID().uuid,
                editable=False,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="uuid",
            field=django_extensions.db.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID().uuid,
                editable=False,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscriptiontransaction",
            name="uuid",
            field=django_extensions.db.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID().uuid,
                editable=False,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="uuid",
            field=django_extensions.db.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID().uuid,
                editable=False,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="planlist",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="planlistdetail",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="plantag",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptiontransaction",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
