# Generated by Django 4.1.4 on 2023-01-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions_api",
            "0011_plancost_uuid_planlist_uuid_planlistdetail_uuid_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planlist",
            name="features",
        ),
        migrations.RemoveField(
            model_name="planlist",
            name="footer",
        ),
        migrations.RemoveField(
            model_name="planlist",
            name="header",
        ),
        migrations.RemoveField(
            model_name="planlist",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="planlistdetail",
            name="html_content",
        ),
        migrations.RemoveField(
            model_name="planlistdetail",
            name="subscribe_button_text",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="feature_ref",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="features",
        ),
        migrations.AlterField(
            model_name="plancost",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]

